version: 2
jobs:
  build:
    environment:
      - IMAGE: 'derekschaefer/circleci-docker-example'
    docker:
      - image: 'circleci/ruby:2.4'
    steps:
      - 'checkout'
      - 'setup_remote_docker'
      - run: 'docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD'
      - run: 'docker build -t $IMAGE:$CIRCLE_SHA1 .'
      - run: 'docker push $IMAGE:$CIRCLE_SHA1'
